### ISSUE TITLE
Complete `say_date()` function

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/dancho-voice-assistant#5]
With commit https://github.com/Stake-And-Rope/dancho-voice-assistant/commit/aaf0af48116da9e2756d03dfbd7b5a7f6148b881 I have uploaded two test function
@KingTheSim, work on say_date() function and complete the code to make Dancho say the current date in format DD:mm:YYYY

**Comment by karastoyanov** [comment]
Related to #2

**Comment by KingTheSim** [comment]
Wrote the say_date() function.

Created a special dates set and dictionary, so the assistant can feel more lively.

Need to decide on what dates can be included as special and to create different replies for each one.

**Comment by karastoyanov** [comment]
With 8c15e54, month pronuntation was fixed.

```python
def say_date():
    cur_date = datetime.date.today().strftime("%d %B %Y")  # <-- Changed the date format to %d %B %Y
    spec_dates = {"17:03", }
    spec_dates_prompts = {"17:03": f"It's my birthday."}
    if not spec_dates.issuperset(cur_date[:-5]):
```
